"""initial schema: tenants, links, partitioned click_events, RLS

Written by hand rather than autogenerated. Autogenerate reflects tables and
indexes; it has no representation for row-level security policies, native
partitioning, database roles, or SECURITY DEFINER functions -- which is most
of what makes this schema correct rather than merely present.

Revision ID: 0001
Revises:
"""

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ------------------------------------------------------------------ roles
    # In a real deployment roles and credentials are provisioned outside
    # migrations -- Terraform, or a secrets manager -- because a migration
    # file is version-controlled and a password in one is a committed secret.
    # Done here because this is a local dev container and the alternative is
    # an out-of-band step nobody would reproduce.
    #
    # NOBYPASSRLS is the point of the whole role: without it the app could
    # opt out of the policies below. NOSUPERUSER for the same reason --
    # superusers bypass RLS unconditionally, FORCE or not.
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'upsk_app') THEN
                CREATE ROLE upsk_app LOGIN PASSWORD 'upsk_app_pw'
                    NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
            END IF;
        END $$;
        """
    )

    # --------------------------------------------------------------- tenants
    op.execute(
        """
        CREATE TABLE tenants (
            id          uuid        PRIMARY KEY,
            name        text        NOT NULL,
            status      varchar(16) NOT NULL DEFAULT 'active',
            created_at  timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_tenants_status CHECK (status IN ('active','suspended'))
        );
        """
    )

    # ----------------------------------------------------------------- links
    op.execute(
        """
        CREATE TABLE links (
            id            uuid        PRIMARY KEY,
            tenant_id     uuid        NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
            created_by    uuid        NOT NULL,
            code          varchar(32) NOT NULL,
            long_url      text        NOT NULL,
            created_at    timestamptz NOT NULL DEFAULT now(),
            expires_at    timestamptz,
            disabled_at   timestamptz,
            tenant_active boolean     NOT NULL DEFAULT true,
            tags          text[],
            CONSTRAINT ck_links_code_entropy CHECK (length(code) >= 7)
        );
        """
    )

    # DATA PLANE: the redirect. Also the constraint that makes the credential
    # mean one thing -- the module's duplicate-code incident is impossible
    # while this exists. Total, not partial: a partial unique index excluding
    # disabled rows would let two disabled links share a code, and re-enabling
    # one turns that into corruption discovered at the worst moment.
    op.execute("CREATE UNIQUE INDEX uq_links_code ON links (code);")

    # MANAGEMENT PLANE: tenant-scoped list with keyset pagination. tenant_id
    # leads (equality predicate), created_at sorts, id breaks ties so
    # pagination is stable across equal timestamps.
    op.execute(
        "CREATE INDEX ix_links_tenant_created "
        "ON links (tenant_id, created_at DESC, id DESC);"
    )

    # ---------------------------------------------------------- click_events
    # RANGE-partitioned now, while empty. Retrofitting partitioning onto a
    # populated table is a full rewrite; doing it here is a few lines and
    # turns Module 7 retention into a metadata operation.
    op.execute(
        """
        CREATE TABLE click_events (
            id          uuid        NOT NULL,
            link_id     uuid        NOT NULL,
            tenant_id   uuid        NOT NULL,
            clicked_at  timestamptz NOT NULL DEFAULT now(),
            user_agent  text,
            referrer    text,
            ip_hash     varchar(64),
            CONSTRAINT pk_click_events PRIMARY KEY (id, clicked_at)
        ) PARTITION BY RANGE (clicked_at);
        """
    )
    # Monthly partitions. Rolling creation belongs to the Module 7 worker;
    # these two cover the present so inserts do not depend on it existing yet.
    op.execute(
        "CREATE TABLE click_events_2026_08 PARTITION OF click_events "
        "FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');"
    )
    op.execute(
        "CREATE TABLE click_events_2026_09 PARTITION OF click_events "
        "FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');"
    )
    # A DEFAULT partition so an insert outside every range fails loudly later
    # rather than erroring at write time on the hot path. The known cost:
    # attaching a new partition fails if rows already sitting in DEFAULT would
    # belong to it, so the Module 7 roller must check DEFAULT is empty.
    op.execute("CREATE TABLE click_events_default PARTITION OF click_events DEFAULT;")

    # Declared on the parent, so every partition inherits them.
    op.execute("CREATE INDEX ix_click_events_link_time ON click_events (link_id, clicked_at);")
    op.execute("CREATE INDEX ix_click_events_tenant_time ON click_events (tenant_id, clicked_at);")

    # ------------------------------------------------------------------- RLS
    # The guarantee the engine was chosen for: a query that forgets
    # WHERE tenant_id = ? returns zero rows instead of everyone's rows.
    #
    # FORCE is not optional. Without it the table owner bypasses its own
    # policies, so the policies would exist, look correct in \d output, and do
    # nothing for anyone connecting as owner.
    for table in ("links", "click_events"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
                USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
                WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
            """
        )
    # USING governs what is visible; WITH CHECK governs what may be written.
    # Both are required -- USING alone would let a caller INSERT a row
    # attributed to another tenant and simply not see it afterwards.
    #
    # The `true` second argument to current_setting makes it return NULL
    # rather than raising when unset, so an unscoped session sees nothing
    # instead of erroring. Fail closed, quietly, on read.

    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON links, click_events TO upsk_app;")
    op.execute("GRANT SELECT ON tenants TO upsk_app;")

    # ------------------------------------------- the redirect / RLS collision
    # GET /r/<code> is public, unauthenticated, and carries no tenant context,
    # so it cannot set app.tenant_id -- under the policy above it would match
    # zero rows and every short link would 404. The two designs collide here.
    #
    # Rejected: widening the policy with an OR on a sentinel tenant value.
    # That puts a magic string inside a security predicate, where any code
    # path that can set the sentinel gets a cross-tenant read.
    #
    # Taken: one narrow SECURITY DEFINER function. It runs as its owner, so it
    # sees across tenants -- but it is the *only* thing that does, it returns
    # exactly three columns, it applies the resolvability rules itself, and
    # every tenant-free read in the system goes through one auditable place.
    # A hole you can name and grep for beats a policy with an exception in it.
    #
    # SET search_path is mandatory, not hygiene: a SECURITY DEFINER function
    # without it can be hijacked by a caller who creates their own `links` in
    # a schema earlier in the search path, and the function would happily read
    # it with owner privileges.
    op.execute(
        """
        CREATE FUNCTION resolve_link(p_code text)
        RETURNS TABLE (link_id uuid, tenant_id uuid, long_url text)
        LANGUAGE sql
        STABLE
        SECURITY DEFINER
        SET search_path = pg_catalog, public
        AS $$
            SELECT l.id, l.tenant_id, l.long_url
            FROM public.links l
            WHERE l.code = p_code
              AND l.tenant_active
              AND l.disabled_at IS NULL
              AND (l.expires_at IS NULL OR l.expires_at > now());
        $$;
        """
    )
    # Default EXECUTE is granted to PUBLIC on new functions. Revoke first,
    # then grant deliberately -- otherwise the narrow capability is available
    # to every role in the cluster.
    op.execute("REVOKE EXECUTE ON FUNCTION resolve_link(text) FROM PUBLIC;")
    op.execute("GRANT EXECUTE ON FUNCTION resolve_link(text) TO upsk_app;")


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS resolve_link(text);")
    op.execute("DROP TABLE IF EXISTS click_events CASCADE;")
    op.execute("DROP TABLE IF EXISTS links CASCADE;")
    op.execute("DROP TABLE IF EXISTS tenants CASCADE;")
    # The role is intentionally not dropped: roles are cluster-wide and may
    # own objects in other databases. A downgrade should not reach outside
    # the schema it created.
